[package]
name = "Rust-LladreDeMuseus"
version = "0.1.0"
authors = ["Xavier Sala <utrescu@gmail.com>"]

[dependencies]
chrono = "0.4.4"
diesel = { version = "1.3.0", features = ["chrono","mysql"] }
dotenv = "0.10"
